ktor {
  deployment {
    port = 8080
  }

  application {
    modules = [ me.vladislav.ApplicationKt.module ]
  }
}

database {
  url = ${?JDBC_DATABASE_URL}
  user = ${?DB_USER}
  password = ${?DB_PASSWORD}
}

jwt {
  secret = ${?JWT_SECRET}
  issuer = ${?JWT_ISSUER}
}

quotes {
  baseUrl = ${?QUOTES_BASE_URL}
}
